Removed required attribute from cardholder name field
Enartia/woo-payment-gateway-for-piraeus-bank pull request #4
Opened 2024-10-30 09:59 UTC by RaymondBakker

The field is now no longer required.

2024-11-01 10:11 UTC, ggeorg0p commented
In the check out page the message in side the text box says “as required” , since its optional its not required, the sentence can change to “ Card holder name is optional by Pireos Bank for Validation”
![image](https://github.com/user-attachments/assets/265a6e98-7aab-4ed7-99fc-374fe065cf02)

2024-11-01 10:12 UTC, ggeorg0p commented
when in the check out page, by selecting pireos pament method the following notices are shown
![image](https://github.com/user-attachments/assets/35ceedde-aaf9-4cc2-81e9-734a3ef22d20)

2024-11-01 10:15 UTC, ggeorg0p requested changes
Please see some comments sent by the QA team

2024-11-13 09:26 UTC, ggeorg0p commented
@uprise10 @RaymondBakker any news?

2024-11-13 11:16 UTC, uprise10 commented
@ggeorg0p Raymond is currently ill now. He will respond as soon as he is back.

2024-11-15 08:13 UTC, closed without merging